### ISSUE TITLE
Installation issue with traefik

### ISSUE THREAD

**Issue by gm-gm-gm** [Awesome-Technologies/synapse-admin#127]
Hi everyone,

I am trying to install synapse-admin along with traefik and have some difficulties. Redirecting administration endpoints seems to work (see logs bellow) but the server keep answering me with 404 Not Found errors. Any help would be appreciated :)

Here is the relevant section of my `docker-compose.yml` file:

```
version: '3.3'

services:
traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    restart: always
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=user@myserver.org"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - "web"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


synapse:
    image: docker.io/matrixdotorg/synapse:v1.30.1
    container_name: synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.synapse-http.rule=Host(`synapse.myserver.org`)"
      - "traefik.http.routers.synapse-https.rule=Host(`synapse.myserver.org`)"
      - "traefik.http.routers.synapse-https.tls.certresolver=mytlschallenge"
      - "traefik.http.middlewares.synapse-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.synapse-http.middlewares=synapse-redirect@docker"
    networks:
      - web
    volumes:
      - synapse_data:/data



  synapse_admin:
    image: awesometechnologies/synapse-admin:0.7.1
    container_name: synapse_admin
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.synapse_admin1-https.rule=(Host(`synapse.myserver.org`) && Path(`/_matrix`))"
      - "traefik.http.routers.synapse_admin2-https.rule=(Host(`synapse.myserver.org`) && Path(`/_synapse/admin`))"
      - "traefik.http.routers.synapse_admin1-https.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.synapse_admin2-https.tls.certresolver=mytlschallenge"
    networks:
      - web



networks:
  web:
    external: true



volumes:
  synapse_data:
```

The synapse-admin gets the requests as suggested by the logs from `docker logs synapse_admin` but nginx returns 404 errors as it does not find the files to serve. It is looking in `/usr/share/nginx/html/_synapse/admin` which look like a proper path to me but my experience with nginx is very limited.

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up

2021/04/06 16:50:47 [error] 34#34: *1 open() "/usr/share/nginx/html/_synapse/admin" failed (2: No such file or directory), client: 172.18.0.3, server: localhost, request: "GET /_synapse/admin HTTP/1.1", host: "synapse.myserver.org"
172.18.0.3 - - [06/Apr/2021:16:50:47 +0000] "GET /_synapse/admin HTTP/1.1" 404 153 

2021/04/06 17:02:20 [error] 34#34: *4 open() "/usr/share/nginx/html/_matrix" failed (2: No such file or directory), client: 172.18.0.3, server: localhost, request: "GET /_matrix HTTP/1.1", host: "synapse.myserver.org"
172.18.0.3 - - [06/Apr/2021:17:02:20 +0000] "GET /_matrix HTTP/1.1" 404 153 
```

All help is welcomed !
