### ISSUE TITLE
Can you please tag a new release?

### ISSUE THREAD

**Issue by aaronraimist** [Awesome-Technologies/synapse-admin#143]
The fix for viewing users was not included in 0.8.0 so people regularly complain that they can't view users using synapse-admin and have to be told to update to the most recent commit.

**Comment by kavemang** [comment]
Hi sorry if this is a dumb question but I'm running this in docker and at some point in the last week or two it went from just the user display not working to all panels giving a "failed to fetch" error, can no longer use the admin, not sure what steps to take as the docker compose just calls back to the git and not an image

**Comment by aaronraimist** [comment]
Yes that's the error I'm talking about. If you are using version 0.8.0 it will not work. You need to be using at least commit 5a5a7143af08e7c6e7f7d3de50855b3fffe875a3.

**Comment by kavemang** [comment]
any advice on how to make docker do that? the only reference to here is in the docker compose:

      context: https://github.com/Awesome-Technologies/synapse-admin.git

is there something I can add to a line like that to force the latest version?

**Comment by aaronraimist** [comment]
I don't really know anything about docker-compose. Based on https://stackoverflow.com/questions/48432881/how-to-specify-commit-in-docker-compose-remote-github-build possibly like this:

```
version: "3"

services:
  synapse-admin:
    container_name: synapse-admin
    hostname: synapse-admin
    image: synapse-admin:latest
    build:
      context: https://github.com/Awesome-Technologies/synapse-admin.git
      # args:
      #   - NODE_OPTIONS="--max_old_space_size=1024"
    ports:
      - "8080:80"
    restart: unless-stopped
```
