### ISSUE TITLE
Add option to provide build args to Dockerfile

### ISSUE THREAD

**Issue by MexHigh** [Awesome-Technologies/synapse-admin#265]
I have the use case, that I want to provide build args to the Dockerfile (`PUBLIC_URL` and `REACT_APP_SERVER`), but when using docker[-compose], you currently cannot to that without cloning the whole repository and building the frontend yourself.

This configuration should be possible in a `docker-compose.yml` file:

```yaml
version: '3'
services:
  synapse-admin:
    build:
      context: https://github.com/Awesome-Technologies/synapse-admin.git
      args:
        PUBLIC_URL: https://admin.<redacted>/synapse
        REACT_APP_SERVER: https://matrix.<redacted>
      ...

```

Related: #167 #159 #11 (which are actually all not resolved)

I'm going to open a PR on this soon.
