### ISSUE TITLE
PUBLIC_URL removed?!

### ISSUE THREAD

**Issue by jeffrson** [Awesome-Technologies/synapse-admin#335]
I read https://github.com/Awesome-Technologies/synapse-admin/issues/322 - and as requested there I'm opening another issue.

How should a prefix like /synapse-admin be handled now? I just upgraded (`docker compose build synapse-admin` with docker-compose.yml according to example on github) and it doesn't work anymore?

**Comment by awesome-michael** [comment]
If you want to build a docker image with a fixed prefix you have to edit the Dockerfile too. See the the changes made in https://github.com/Awesome-Technologies/synapse-admin/commit/9b43d41040b79cc8ad240dbadc66098bc8231c2b (add the ARG and edit the RUN command).

**Comment by jeffrson** [comment]
Yes, I saw those changes - but I don't understand. Do you mean I should re-add the lines to Dockerfile that you'd removed?

As the docs (README.md) suggest, I use docker-compose.yml with

```
services:
  synapse-admin:
    build:
      context: https://github.com/Awesome-Technologies/synapse-admin.git
      args:
        ...
        - PUBLIC_URL=/synapse-admin
        ...
```

There's no way to edit Dockerfile whatsoever.

I'm running /synapse-admin through nginx reverse proxy and I don't see how it is intended now to be used.
