### ISSUE TITLE
Error with synapse-admin and HTTPS

### ISSUE THREAD

**Issue by acexiis** [Awesome-Technologies/synapse-admin#446]
Hello everyone,

I have a problem to make synapse-admin (docker) and HTTPS.

My docker-compose is : 
```
synapse-admin:
      container_name: synapse-admin
      hostname: synapse-admin
      image: awesometechnologies/synapse-admin:latest
      build:
        context: https://github.com/Awesome-Technologies/synapse-admin.git
        args:
      #   - NODE_OPTIONS="--max_old_space_size=1024"
      #   # see #266, PUBLIC_URL must be without surrounding quotation marks
        - PUBLIC_URL=/synapse-admin
        - REACT_APP_SERVER="https://mydomain.fr"
      ports:
        - "8083:80"
      restart: unless-stopped
```

And my RP config for synapse-admin is : 
```
    location ~ ^(/_matrix|/_synapse/client|/_synapse/admin|/_synapse/metrics) {

      proxy_set_header        Host $host:$server_port;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;
      proxy_pass http://matrix;
      proxy_redirect http:// https://;
      add_header Pragma "no-cache";
    }

    location /synapse-admin {
     #return 301 http://mydomain.fr:8083;
     absolute_redirect off;
     proxy_set_header        Host $host:$server_port;
     proxy_pass http://synapse_admin;
    }
```

with the upstream : 
```
upstream matrix {
  server 127.0.0.1:8008 fail_timeout=0;
}

upstream synapse_admin {
  server 127.0.0.1:8083 fail_timeout=0;
}

```

For the location /synapse-admin if I use only : return 301 http://mydomain.fr:8083; → that works in HTTP mode. But with the actual configuration it does not work, and I have this logs inside the synapse-admin container : 

```
68.94.224.181 - - [02/Jan/2024:18:37:40 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"
2024/01/02 18:37:58 [error] 34#34: *5 open() "/usr/share/nginx/html/synapse-admin" failed (2: No such file or directory), client: 172.31.0.1, server: localhost, request: "GET /synapse-admin HTTP/1.0", host: "mydomain.fr:443"
```

Any ideas ?

Thanks a lot
