### ISSUE TITLE
Connexion Homeserver URL

### ISSUE THREAD

**Issue by acexiis** [Awesome-Technologies/synapse-admin#449]
Hello,

I have two environment PPRD and TEST with the exact same configuration for synapse-admin.
```
synapse-admin:
      container_name: synapse-admin
      hostname: synapse-admin
      image: awesometechnologies/synapse-admin:latest
      ports:
        - "8083:80"
      restart: unless-stopped
```

On the connection page, my TEST environment has an empty field for Homerserver URL and I can fill it. But my PPRD environment has the same field already fill with `"https://mydomain.fr"` and I can't change it, the field is unchangeable.

Someone have an idea why this difference?
Thanks a lot.
