### ISSUE TITLE
`%20` Added to Paths When Using `BASE_PATH="/"` in Docker Compose

### ISSUE THREAD

**Issue by 0xA1-devops** [Awesome-Technologies/synapse-admin#642]
## Description

When setting `BASE_PATH="/"` in the Docker Compose configuration for `synapse-admin`, URLs are incorrectly encoded with `%20`, causing issues with request routing. 

### Example

Given the following `docker-compose.yml`:
```yaml
services:
  synapse-admin:
    container_name: synapse-admin
    build:
      context: .
      args:
        - BASE_PATH=/
    ports:
      - "127.0.0.1:50000:80"
    restart: unless-stopped
```

Requests through an external proxy (e.g., Nginx) such as:

```
http://your-domain/synapse-admin/
```

may result in URLs like:

```
http://127.0.0.1:50000/%20/synapse-admin/assets/index.js
```

### Suggested Fix

Change BASE_PATH="/" to BASE_PATH=/ in the docker-compose.yml file to avoid encoding issues:

```yaml
args:
  - BASE_PATH=/
```

### Environment

- **Image:** awesometechnologies/synapse-admin:latest
- **Deployment Method:** Docker Compose
- **Reverse Proxy:** Nginx
- **Build Source:** master (9fc005032c5b578fe5f360844ba5db69d870fb78)
- **Docker version:** 20.10.24+dfsg1
- **docker-compose version:** 1.29.2
