### ISSUE TITLE
Cannot get `config.json`

### ISSUE THREAD

**Issue by paulbdavis** [Awesome-Technologies/synapse-admin#644]
I have synapse admin set up on a subpath of my matrix server domain

`docker-compose.yaml`:
```yaml
  synapse-admin:
    container_name: synapse-admin
    hostname: synapse-admin
    environment:
      REACT_APP_SERVER: http://synapse:8008
    ports:
      - 8450:80
    build:
      context: https://github.com/Awesome-Technologies/synapse-admin.git
      args:
        - BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
        - BASE_PATH=/synadm
    restart: unless-stopped
```

nginx config:
```nginx
    location /synadm {
        # Set proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # These are important to support WebSockets
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://XXX.XXX.XXX.XXX:8450/;
        rewrite ^/synadm(/.*)$ $1 break;
    }
```

It properly gets the `index-*.js` file just fine, but then chokes trying to get the `config.json` file, it seems to not be using the supplied base url.
