### ISSUE TITLE
help with React Admin

### ISSUE THREAD

**Issue by SpsZaPIZZA** [Awesome-Technologies/synapse-admin#669]
Hey, everybody! Can you tell me what I'm doing wrong? I have a “Something went wrong” error in REACT Admin.

Error
```
index-VL_fdGJp.js:40 Error
    at Et (index-VL_fdGJp.js:75:1012)
    at index-VL_fdGJp.js:85:8872
    at index-VL_fdGJp.js:9:3866
    at index-VL_fdGJp.js:9:3270
    at Qg (index-VL_fdGJp.js:9:2481)
    at Qg (index-VL_fdGJp.js:9:2787)
    at Qg (index-VL_fdGJp.js:9:2787)
    at ig (index-VL_fdGJp.js:9:3236)
    at Object.forEach (index-VL_fdGJp.js:9:3848)
    at IE (index-VL_fdGJp.js:85:8725)
```
![Image](https://github.com/user-attachments/assets/d2824a81-0e8d-402f-b2f6-a8e0da13121f)

**docker-compose:**
```
services:
  synapse-admin:
    image: awesometechnologies/synapse-admin:latest
    container_name: synapse-admin
    hostname: synapse-admin
    volumes:
      - /opt/synapse-admin/public/config.json:/app/config.json:ro
    ports:
      - "8088:80"
    restart: unless-stopped

```
**config:**
```
{
  "restrictBaseUrl": "https://matrix.orenpay.ru"
}
```

Please help me :)
